name: VelocityArenas
version: '${project.version}'
main: dev.manere.velocityarenas.VelocityArenas
api-version: '1.17'
depend:
  - FastAsyncWorldEdit

permissions:
  velocity.staff:
    default: op

commands:
  arenaregen:
    permission: velocity.staff
